# Generated by Django 5.2.4 on 2025-08-29 21:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConvesationMessage',
            new_name='ConversationMessage',
        ),
    ]
